name: Python Lint
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main", "feature*" ]
    paths:
      - 'python/**'

defaults:
  run:
    working-directory: python

jobs:

  ruff:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.12"]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - run: echo "/root/.local/bin" >> $GITHUB_PATH
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
          cache-dependency-path: "python/pyproject.toml"
      - name: Install SemanticKernel
        run: poetry install --no-ansi
      - name: Run lint
        run: |
          poetry run pip install --upgrade ruff --pre
          poetry run ruff check .

  black:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.12"]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - run: echo "/root/.local/bin" >> $GITHUB_PATH
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
          cache-dependency-path: "python/pyproject.toml"
      - name: Add ruff
        run: poetry install --no-ansi
      - name: Run lint
        run: |
          poetry run pip install --upgrade black[jupyter] --pre
          poetry run black --check .
